name: Run Tests
on:
  push:
    branches-ignore:
      - main
      - dev
  pull_request:
    branches: ['**']
  

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      
      - name: Install dep
        run: npm install

      - name: Run tests
        run: npm test